### ISSUE TITLE
Source for other modules is missing.... source can't be built.

### ISSUE THREAD

**Issue by jaxuk** [ventrian/News-Articles#1]
Hey Scott,

I've just been trying to make some changes to the source but I can't build the solution properly as the source for LatestArticles / Comments / Archives / Search are missing. 

Hope you can upload these to the git.

Thanks

**Comment by sjmcculloch** [comment]
Hi @jaxuk - they are there - you can see them in the source tree: 

https://github.com/ventrian/News-Articles

e.g. LatestArticles.ascx.vb

You may need to update the module definitions to point them at the correct location or move those files.

**Comment by jaxuk** [comment]
Thanks for the quick response - Do'h yeah I see them... OK that's not the issue I've got... Back to debugging.
