### ISSUE TITLE
Downloadable install release?

### ISSUE THREAD

**Issue by b-creative** [ventrian/News-Articles#10]
Hi,
I see some activity in this project, but am I missing something and is there no release available to download yet? I have no prior experience with Github so I'm not aware of any do-it-yourself actions...
afaics there's just the 0.9.11 release, correct?

**Comment by NerdyParker** [comment]
Use the following install package: https://github.com/ventrian/News-Articles/blob/master/Installs/NewsArticles.00.09.11.zip

FYI - The module is not currently compatible with DNN 9.2.2.

**Comment by skamphuis** [comment]
We'll be fixing the GitHub page asap, with downloadable releases. Untill then,, download it [here](https://github.com/ventrian/News-Articles/tree/master/Installs).
