### ISSUE TITLE
Upgrade to 9.2

### ISSUE THREAD

**Issue by alpacadevelopment** [ventrian/News-Articles#15]
I just upgraded to 9.2 and the module did break (vague I know). Stack trace...any thoughts...

An error has occurred. DotNetNuke.Services.Exceptions.ModuleLoadException: Method not found: 'System.String DotNetNuke.Entities.Modules.ModuleInfo.get_AuthorizedEditRoles()'. ---> System.MissingMethodException: Method not found: 'System.String DotNetNuke.Entities.Modules.ModuleInfo.get_AuthorizedEditRoles()'. at Ventrian.NewsArticles.ArticleSettings.get_IsAdmin() at Ventrian.NewsArticles.ArticleSettings.get_IsSubmitter() at Ventrian.NewsArticles.TokenProcessor.ProcessMenuItem(String token, ControlCollection& objPlaceHolder, LayoutController objLayoutController, NewsArticleModuleBase moduleContext, Int32& iPtr, String[] templateArray, MenuOptionType selectedMenu) at Ventrian.NewsArticles.TokenProcessor.ProcessMenu(ControlCollection& placeHolder, NewsArticleModuleBase& moduleContext, MenuOptionType selectedMenu) at Ventrian.NewsArticles.ucHeader.Page_PreRender(Object sender, EventArgs e) --- End of inner exception stack trace --

**Comment by mortezakermani** [comment]
Hi @alpacadevelopment,

benvis.com just published a version of News Articles modules which is compatible with DNN 7.x, DNN 8.x and DNN 9.x (including DNN 9.2 and later) at [dnn store](https://store.dnnsoftware.com/home/product-details/ventrian-news-articles-companions).

They also have 4 complementary modules for News Articles.

**Comment by thenotandy** [comment]
There is a working install at https://github.com/NerdyParker/News-Articles/tree/master/Installs

**Comment by skamphuis** [comment]
Pullrequest #14 contains a 0.10.00 install package that should work. It also removes the use of flash for uploads. I need a bit of time to make it a release or release candidate soon.
