### ISSUE TITLE
Form validation is broken when other forms on the page

### ISSUE THREAD

**Issue by jbrinkman** [ventrian/News-Articles#21]
When creating new articles, there is no validation group set on the form, as a result, if additional forms (like a login form) are on the page then the check for "Page.IsValid" in cmdSaveArticle_Click will return false and the form will not be saved.  To correct this, formvalidators and form submission buttons should be assigned to a common validation group so that they do not clash with other forms which might appear on the DNN page.

**Comment by skamphuis** [comment]
Validation groups where added (by @jbrinkman if I'm not mistaken)
