### ISSUE TITLE
Do not allow images pasted into the text

### ISSUE THREAD

**Issue by vmasanas** [ventrian/News-Articles#25]
We've found in a number of sites that people just copy/past images from their image editor.
This results on the image being embedded on the html as Base64. This causes the html to grow a lot and we've had some performance problems on the database then.

Would it be interesting to have a global option "Allow embedded images" that the admin could enable/disable for this? Is the setting were enabled then it would keep doing the same as now.
If disabled, it would render an error when trying to save the Article.

What do you think?

**Comment by Timo-Breumelhof** [comment]
I think you can prevent this using a setting in CKEditor..

**Comment by vmasanas** [comment]
Any idea where this setting is?

**Comment by Timo-Breumelhof** [comment]
I have done the opposite for Open Content as it strips out anything you enter in the Source view by default. That setting is "extraAllowedContent" I forgot the name of the setting that does the opposite but it does exist.
