### ISSUE TITLE
Upload images - DNN 9 Issue

### ISSUE THREAD

**Issue by maduranga001** [ventrian/News-Articles#3]
I upgraded my site to DNN 9 and I can see an issue like this. cannot upload images and browse button has missing to select images from our local machine.

Please, can you help me how to resolve this on latest DNN 9.1.1 ?

![nws](https://user-images.githubusercontent.com/10365085/32141546-635c42d6-bca9-11e7-98cb-5dcb692f013d.jpg)

Still, we are using this module as we have lots of custom modifications after your final release. So migrating from this would be not easy and have to stick with the module.

Your support is much appreciated.

**Comment by Scippy** [comment]
It seems to be missing the flash player pluging for your web browser.

**Comment by maduranga001** [comment]
Thank you for the reply. I used the same browser before I upgrade DNN 7.20 to DNN 9.1.1
This issue came just after upgrading to DNN 9.1.1 and I did not change anything on the browser.

My other admin also has this issue.

Please, advise.

**Comment by jaxuk** [comment]
This does still work when using chrome. When you click that area where the
button should be chrome will ask you if you want to allow flash to run or
block it. You need to allow it.

Chrome will not do this forever. Eventually they will drop fladh support
like firefox and this will no longer work.

**Comment by maduranga001** [comment]
Woohoo.. Yes. It is working now. Great.!
Thank you very much.

**Comment by maduranga001** [comment]
Hi,

Again there is the issue. I do not see flash plugin issue anymore. But not the file upload control too.
![nws2](https://user-images.githubusercontent.com/10365085/32590214-3799d638-c53f-11e7-90ae-8748f2ac29cb.jpg)

Please, can you advise me how to fix this. I just upgraded the DNN site to DNN 9.1.1 and didn't do any changes to the site.
Anyway, it worked with the previous solution for flash plugin and seems to be missing the control again somehow.

Appreciate your support.

**Comment by maduranga001** [comment]
Any idea how to fix uploading files/images control issue? Please, can you help me?

**Comment by jaxuk** [comment]
What version of chrome are you using and on what operating system??

**Comment by maduranga001** [comment]
I am using 
Google Chrome Version 62.0.3202.89 (Official Build) (64-bit) and Windows 7 Ultimate.

This is same for other admins PCs too.

Please help how to get back the file upload control.

Thank You!

**Comment by jaxuk** [comment]
Have a look at this
https://support.google.com/chrome/answer/6258784?co=GENIE.Platform%3DDesktop&hl=en

Does that help?

**Comment by maduranga001** [comment]
I've already done this. Then the control visible for a day. Somehow it is disappeared again. This is not only my PC  and browsers. We checked it on different PCs too with different admin user accounts.

We checked on IE and FF too. Still not visible the control.

Please help.

**Comment by jaxuk** [comment]
Do you have errors in the console of chrome after the article admin page
loads?

**Comment by maduranga001** [comment]
I am not seeing any errors. How can I check if I am getting any loading errors?

No any issues reported on DNn website admin logs too.

**Comment by maduranga001** [comment]
Now I am just noticing this.

Only "Edit an existing article" page has this issue. "Add a new article" window is loading the file upload control after a second.

Any idea? Why is it dissapering like this. Somehow I was checking edit window as I needed to change some images.

Thank you for supporting.

**Comment by maduranga001** [comment]
The problem is on the edit an existing article window now. Please, can you help to fix this?

But Firefox and IE are not loading the control for both edit and new article windows.

**Comment by jaxuk** [comment]
Follow this https://developers.google.com/web/tools/chrome-devtools/console/
and post any errors you see here.

**Comment by maduranga001** [comment]
Ok. Thank you!

I do not know if this is the correct error. I can see so many red messages. 

`Uncaught TypeError: instance.attr(...).replace is not a function
    at HTMLAnchorElement.<anonymous> (dnn.jquery.js?cdv=298:4279)
    at Function.each (jquery-1.3.2.min.js:12)
    at init.each (jquery-1.3.2.min.js:12)
    at HTMLDocument.dnnInitCustomisedCtrls (dnn.jquery.js?cdv=298:4269)
    at Function.<anonymous> (jquery-1.3.2.min.js:19)
    at Function.each (jquery-1.3.2.min.js:12)
    at Function.ready (jquery-1.3.2.min.js:19)
    at HTMLDocument.<anonymous> (jquery-1.3.2.min.js:19)
[www.mysite.com-1510401138304.log](https://github.com/ventrian/News-Articles/files/1463718/www.mysite.com-1510401138304.log)
`

I've attached a copy of all with this too. Please open the log file in VS and then it will be readable.

Thank you for supporting.

**Comment by jaxuk** [comment]
Ok you have some debugging to do...

The flash object which enables the uploads is initated by javascript. The
error you have posted most likely occours before the flash object gets
initiated and prevents any more javascript running from the onload event.
So you do not see the uploader.

**Comment by jaxuk** [comment]
Ps. I wont be near a computer until Monday. I will have a look at the logs
then to see if I can help aanymore.

On 11 Nov 2017 12:44 pm, "Jacques Woolston" <jacques@yedit.co.uk> wrote:

Ok you have some debugging to do...

The flash object which enables the uploads is initated by javascript. The
error you have posted most likely occours before the flash object gets
initiated and prevents any more javascript running from the onload event.
So you do not see the uploader.

**Comment by maduranga001** [comment]
really appreciate your support. Hope you can find the solution for this. I am not good at javascript debugging.

Thank you and waiting for your next supportive answer.

If you want, I can send you the page link and admin access private message. (if it is possible to do)

**Comment by maduranga001** [comment]
I am using Google Chrome 
Version 67.0.3396.79 (Official Build) (64-bit) now.

I can not see the upload button now. Please, can you advise me how to fix this? It is not asking to install flash message or anything. The upload button has missing now.

Plese, advise. Thank you!

**Comment by theJRK** [comment]
News Articles registers version 1.3.2 of jquery on the edit view to support the uploader.  This conflicts with core jquery, specifically the .on method which was introduced in jquery 1.7.  Deleting the contents (suggest leaving a comment) of /DesktopModules/DNNForge - NewsArticles/Includes/Uploader/jquery-1.3.2.min.js resolved the conflicts we were experiencing.  I normally wouldn't advise this approach but investing in a longer term fix for a module that is no longer being maintained seems like folly.

**Comment by mastercodefu** [comment]
Any chance this can be added as a core module?

Regards
Craig

On 13 Jul 2018, at 18:14, Joel Koenigs <notifications@github.com<mailto:notifications@github.com>> wrote:


News Articles registers version 1.3.2 of jquery on the edit view to support the uploader. This conflicts with core jquery, specifically the .on method which was introduced in jquery 1.7. Deleting the contents (suggest leaving a comment) of /DesktopModules/DNNForge - NewsArticles/Includes/Uploader/jquery-1.3.2.min.js resolved the conflicts we were experiencing. I normally wouldn't advise this approach but investing in a longer term fix for a module that is no longer being maintained seems like folly.

**Comment by Timo-Breumelhof** [comment]
FYI: https://github.com/ventrian/News-Articles/pull/14
