### ISSUE TITLE
Can not update Latest Articles template setting

### ISSUE THREAD

**Issue by fntuncer** [ventrian/News-Articles#32]
Can not update Latest Articles template setting. HTML Body field accepts only 50 caharacters. Also update button not updating. DNN Platform 9.3.2 and News Articles 00.11.03 both are new install.

**Comment by fntuncer** [comment]
Updating module template setting but HTML Body, footer and header fields are accepts only 50 characters

**Comment by perezandres** [comment]
I've found same issue. Easiest workout is to edit the module template using FTP (it's in path \DesktopModules\DnnForge - LatestArticles\Templates\moduleId)

**Comment by Timo-Breumelhof** [comment]
Hmm strange. I just tested this and I have 392 characters in my latest template body text field and it updates just fine..

**Comment by Timo-Breumelhof** [comment]
I do see this https://github.com/ventrian/News-Articles/blob/465d0122b1d8e270bf6e551ddcbc7b42127d5588/LatestArticlesOptions.ascx#L258 but my browser seems to ignore that. What browser are you using?
Could you try editing this file:

\DesktopModules\DnnForge - LatestArticles\LatestArticlesOptions.ascx

Find the line mentioned above and remove the maxlength="50"  and let us know if that helps :-)

**Comment by perezandres** [comment]
I was using Chrome, but I kind of remember same issue with Firefox. I've removed that 50 char limit and now I can save my template.  Reviewing the code I can see same limit for the rest of fields: header, footer, NoArticles,...
Thank you for the clue, Timo ;-)
