### ISSUE TITLE
Article title dropped from URL on shared portal

### ISSUE THREAD

**Issue by jabriner** [ventrian/News-Articles#38]
Article title dropped from URL on shared portal. Site still presents correctly but cannot share with Facebook. Object removed error

On Shared portal:
<form method="post" action="/Home/ID/1132" id="Form" enctype="multipart/form-data">

DNN 9.2.2, News Articles 11.03

**Comment by Timo-Breumelhof** [comment]
Sorry, but I have no idea what the issue is, can you please explain how to reproduce this?

**Comment by jabriner** [comment]
I could not reproduce on a new install of DNN.  The site has been upgraded since DNN 4.0, I removed everything I could find with this module then reinstalled and imported old articles. Works now, apologies for not updating here.

The problem was: With content sharing enabled the child portal was showing  .../ID/927/ArticleTitle but it would drop the article title, therefore the article would display correctly on the website but could not share out to social media due to broke link. .../ID/927/

**Comment by Timo-Breumelhof** [comment]
ok thank you for the feedback :-)
