### ISSUE TITLE
How to insert a Read more link in the body of an article

### ISSUE THREAD

**Issue by ChaoticGood76** [ventrian/News-Articles#45]
Hello. I would like to ask if it is possible and what is the procedure, to enter a Read More link in the body of an article, to work as an expandable text for the rest of the text in the body of an article. For example, i have an article with 5 text paragraphs in its body, and i want only the first paragraph to be shown when the user first enters to the article and the the rest of the article (the remaining 4 paragraphs with text) to be shown only if the user clicks in a Read More link in the body of an article. Thank you very much for your time.

**Comment by Timo-Breumelhof** [comment]
Yes you can do that but you would have to adjust the template and you need html / css knowledge

**Comment by RichardHowells** [comment]
As Timo says, you can do this.  I would question if it's worth the effort.  

The user's choices are to look at a short summary in a list (that's the module's front page), or to click into a single article.  

Once they have chosen to look at a single article it seems mean to hide some of it, making them click again to see the balance.

**Comment by Timo-Breumelhof** [comment]
IMO not a module issue, but a html / css question
