### ISSUE TITLE
bullet point in summary does not reflect in latest articles

### ISSUE THREAD

**Issue by songfeng11** [ventrian/News-Articles#48]
i have added bullet points in the summary of an article, it appears normally on the news artciles modules but does not reflect on latest articles.

i have used [SUMMARY:150] on latest articles.

**Comment by Timo-Breumelhof** [comment]
AFAIK this is by design and all HTML is removed in the summary

**Comment by songfeng11** [comment]
is there any way to not make that happen?

**Comment by songfeng11** [comment]
by the way, is there any way to change the date format when publishing/updating announcements?

**Comment by Timo-Breumelhof** [comment]
I don't think there's an option for that.
You could use a custom field is you want to get around this.

**Comment by songfeng11** [comment]
how can i go about using this custom field?

**Comment by Timo-Breumelhof** [comment]
If you scroll all the way down this page you will see the tokens that can be used:
https://github.com/ventrian/News-Articles
