### ISSUE TITLE
Good News to all "News Articles" lovers

### ISSUE THREAD

**Issue by mortezakermani** [ventrian/News-Articles#54]
Ryan at benvis.com just released a package of 8 new widgets, 6 new templates, 1 new dnn theme along with a free developed version of News Articles called "Advanced News Articles" with +200 new features/options at dnn store. [click here to learn more](https://store.dnnsoftware.com/home/product-details/advanced-news-articles).

Advanced News Articles has features that make this module even more powerful. JavaScript bulk uploader, Slug for each article (without id in url), google richsnippets for content and star rating, option to add image, music and video inside the body of article with a click, re designed settings and [admin panel](https://s3.amazonaws.com/Snowcovered_MyFiles/31931_NA-AdminOptions.png) of all modules based on dnn +7 layout, tag autosuggest, integration with dnn sitemap and a lot of more features and options...

[You are interested to see a live demo, then click here.](http://dnn.benvis.com/journalist)

**Comment by Scippy** [comment]
it would be great if an important evolution were made on the property angent module and not on this one where there is already a wide choice of products in the store

**Comment by Timo-Breumelhof** [comment]
@Scippy I don't think that is ever going to happen as there are 2 open source alternatives that are up to date and much better TBH; Open Content and 2SXC. IMO you should consider Property Agent as a dead end and look for alternatives.

**Comment by Timo-Breumelhof** [comment]
@mortezakermani you can make announcements like this @ https://dnncommunity.org/forums/aff/10
