### ISSUE TITLE
Upload images button | Adobe Flash Player EOL

### ISSUE THREAD

**Issue by mmojadad** [ventrian/News-Articles#57]
Hello
I cannot upload images and browse button has missing to select images from our local machine.
Adobe Flash Player EOL, What will be solution?
https://www.adobe.com/products/flashplayer/end-of-life.html

**Comment by Timo-Breumelhof** [comment]
Upgrade the module?

**Comment by mmojadad** [comment]
@Timo-Breumelhof 
Thank you, I will upgrade the module and try again.

**Comment by mmojadad** [comment]
@Timo-Breumelhof 
Thank you, I will upgrade the module and try again.
