### ISSUE TITLE
Upload image doesn't work in DNN 9.81

### ISSUE THREAD

**Issue by idasbv** [ventrian/News-Articles#59]
When you upload an image to an article it doesn't show the image:

There is an error in the eventlog:
Message:Job #4b561ed9-0be4-4162-90c4-47490f34eb1d (Item dnnfile-2184 from portal 1) is skipped and will be removed from queue. Job details: {"Guid":"4b561ed9-0be4-4162-90c4-47490f34eb1d","Priority":5,"Due":"2021-02-02T14:07:45.843+00:00","Action":"add update","BehaviorId":12,"PortalId":1,"TabId":-1,"ModuleId":-1,"ItemId":"dnnfile-2184","Contents":null,"ContentType":"image/jpeg","Metadata":{"PortalId":1,"ItemId":null,"Title":"","LockTitle":false,"OriginalId":null,"OriginalName":null,"OriginalPath":null,"

Any idea what can be the problem?

**Comment by Timo-Breumelhof** [comment]
I just tested this in 9.9.1 and it works as expected
