### ISSUE TITLE
Error in DNN 9.2.0

### ISSUE THREAD

**Issue by b-creative** [ventrian/News-Articles#6]
Anyone experienced this error (visible when logged in as admin) aswell? Cannot view or edit the articles or settings anymore...
I'd hate to replace ALL my news articles/latest articles now,,,

`
DotNetNuke.Services.Exceptions.ModuleLoadException: Method not found: 'System.String DotNetNuke.Entities.Modules.ModuleInfo.get_AuthorizedEditRoles()'. ---> System.MissingMethodException: Method not found: 'System.String DotNetNuke.Entities.Modules.ModuleInfo.get_AuthorizedEditRoles()'. at Ventrian.NewsArticles.ArticleSettings.get_IsAdmin() at Ventrian.NewsArticles.ArticleSettings.get_IsSubmitter() at Ventrian.NewsArticles.TokenProcessor.ProcessMenuItem(String token, ControlCollection& objPlaceHolder, LayoutController objLayoutController, NewsArticleModuleBase moduleContext, Int32& iPtr, String[] templateArray, MenuOptionType selectedMenu) at Ventrian.NewsArticles.TokenProcessor.ProcessMenu(ControlCollection& placeHolder, NewsArticleModuleBase& moduleContext, MenuOptionType selectedMenu) at Ventrian.NewsArticles.ucHeader.Page_PreRender(Object sender, EventArgs e) --- End of inner exception stack trace ---
`

From the Log:

**ModuleId**:-1
**ModuleDefId**:-1
**AbsoluteURL**:/Default.aspx
**DefaultDataProvider**:DotNetNuke.Data.SqlDataProvider, DotNetNuke
AssemblyVersion:9.2.0
**PortalId**:0
**Message**:Method not found: 'System.String DotNetNuke.Entities.Modules.ModuleInfo.get_AuthorizedEditRoles()'.
**InnerMessage**:Method not found: 'System.String DotNetNuke.Entities.Modules.ModuleInfo.get_AuthorizedEditRoles()'.
**InnerStackTrace:**
at Ventrian.NewsArticles.ArticleSettings.get_IsAdmin() at Ventrian.NewsArticles.ArticleSettings.get_IsSubmitter() at Ventrian.NewsArticles.TokenProcessor.ProcessMenuItem(String token, ControlCollection& objPlaceHolder, LayoutController objLayoutController, NewsArticleModuleBase moduleContext, Int32& iPtr, String[] templateArray, MenuOptionType selectedMenu) at Ventrian.NewsArticles.TokenProcessor.ProcessMenu(ControlCollection& placeHolder, NewsArticleModuleBase& moduleContext, MenuOptionType selectedMenu) at Ventrian.NewsArticles.ucHeader.Page_PreRender(Object sender, EventArgs e)

**Comment by jaxuk** [comment]
The breaking changes to 9.2.0 I believe break NA as the methods used by NA
no longer exist in DNN.

I have been working on a replacement open source module that will do
everything NA does and will import all NA data, redirect NA urls etc.

It's not quite ready yet but it should be ready for testing out in a couple
of weeks.

**Comment by b-creative** [comment]
Wauw, would be great! If I can test for you, let me know...

**Comment by cklenk** [comment]
We would be interested in that solution too!!

**Comment by sjmcculloch** [comment]
I'm patching the build over the next week - we've had someone sponsor the updates.

**Comment by vincentparrett** [comment]
Any update on this.. currently working through upgrading my site and this is blocking.

**Comment by jag64551** [comment]
Hi Scott, just wondering if you had an ETA on this? Thanks

**Comment by NerdyParker** [comment]
@jaxuk Are you still working on this? I'd love to help with development.

**Comment by NerdyParker** [comment]
@jaxuk @sjmcculloch  Are either of you still working on this? I'd love to help with development

**Comment by mastercodefu** [comment]
Am really interested as well.

**Comment by jaxuk** [comment]
I am indeed. Busy moving house right now but next couple of weeks and I
will have a public beta ready.

**Comment by NerdyParker** [comment]
@jaxuk I've been working on this for past day or so. I have the public facing components updated and am finishing up some issues on the submit article screen.

**Comment by NerdyParker** [comment]
I have the updates complete here: https://github.com/NerdyParker/News-Articles

However, I'm not sure how to build the install packages for this particular module. Should be able to drop the Ventrian.NewsArticles.dll in your DNN directory. Please test and backup before deploying any of this to a production server.

**Comment by kandiban99** [comment]
Hi,

We have installed module in Dnn 9.2.... same issue occurs.
Module downloaded from https://github.com/NerdyParker/News-Articles

**Location path**: News-Articles-master\News-Articles-master\Installs

Please advice... waiting for your quick reply.

Thanks,
Kandiban. D

**Comment by vincentparrett** [comment]
I've given up on this, moved the content to my blogs module and added a million redirects...

**Comment by kandiban99** [comment]
Hi NerdyParker,

Any update on this module?

Thanks,
Kandiban. D

**Comment by NerdyParker** [comment]
@kandiban99 You'll need to compile and drop the Ventrian.NewsArticles.dll in your bin folder. I'm not able to package it as an install because I don't have the correct build script.

**Comment by kandiban99** [comment]
Hi NerdyParker,

Thank you so much... Now news article module works fine...

Thanks,
Kandiban. D

**Comment by Timo-Breumelhof** [comment]
FYI: https://github.com/ventrian/News-Articles/pull/14
