### ISSUE TITLE
Core Search Integration don't work

### ISSUE THREAD

**Issue by Scippy** [ventrian/News-Articles#66]
I've enabled "Allow Core Search Integration?" options in Main Options, but searching with DNN core search nothing published in ventrian news articles is founded.
am I wrong something or is there a problem?

**Comment by Scippy** [comment]
is anyone able to give me feedback about it?
Thanks!

**Comment by skamphuis** [comment]
I didn't dive into the details of this, but it looks like DNN doesn't support the old ISearchable interface anymore, which was used by NewsArticles. If that's true, that basically means DNN isn't asking NA for it's content anymore, to use for the core search.

**Comment by Scippy** [comment]
Any chance to make it work again?

**Comment by skamphuis** [comment]
If I'm not mistaken, the ISearchable interface News Articles is using for DNN search integration, is not supported anymore (and hasn't been supported for a while already). Not sure if anyone else has, but I don't have any plans to change that, sorry.

**Comment by Scippy** [comment]
@skamphuis thank you for your reply but What's the reason? takes too long to fix?

**Comment by skamphuis** [comment]
> @skamphuis thank you for your reply but What's the reason? Maybe it takes too long time to fix?

Well, I guess it should be done in under 4 hours or something like that. But it's not a fun thing to make and I believe people would be better of by using that time to implement another solution that will support DNN Core Search integration. [We use OpenContent](https://www.40fingers.net/Blog/ID/169/Moving-15000-articles-from-Ventrian-NewsArticles-to-OpenContent) for example.

**Comment by Scippy** [comment]
@skamphuis Do you mean then that you will no longer support this module and that we should stop using it?

**Comment by skamphuis** [comment]
I think everyone should have stopped using it several years ago, but of course it's not always that easy. We were happy to be able to do some mainenance occasionally, together with several other contributors. That way there where options when there as a need in situations where migration to another module was not, or not yet, an option for various reasons. As it says in the readme file: 

> We are mainly fixing issues for our clients, so don't expect 40F to fix all issues. Pull request are always welcome. :-)
We are currently in the process of converting our clients News Articles modules to Open Content and will stop using and supporting this module in the near future."

Hope this explains things a bit?

**Comment by skamphuis** [comment]
By the way, @Timo-Breumelhof and I are looking into fixing one more release soon, with a few pull requests that have not been incorporated yet, "to wrap things up".
