### ISSUE TITLE
Filter by Max Age (days) not working

### ISSUE THREAD

**Issue by jag64551** [ventrian/News-Articles#7]
Anyone else have issues with the Filter by Max Age not applying? I set it to something, and all articles are shown no matter what. Not sure what to do to get it working. Thanks

**Comment by sjmcculloch** [comment]
What version of DNN & articles?

**Comment by jag64551** [comment]
Hi Scott - DNN 9.1.1, NA 0.9.11
Thanks

**Comment by jag64551** [comment]
Hi Scott, just wondering if you had any further thoughts on this. Thanks!
