### ISSUE TITLE
Missing Reference

### ISSUE THREAD

**Issue by cklenk** [ventrian/News-Articles#8]
Hello, any chance you have your ImageResizer project somewhere? I see the NewsArticles project references it.

Thank you.

**Comment by sjmcculloch** [comment]
I have the compiled DLL - it was a proprietary component - why do you need the non-compiled version?

**Comment by cklenk** [comment]
I don't, but the project needs it to build. And I don't see it included in your libraries folder. Thank you.

**Comment by skamphuis** [comment]
It's in the install package. The project references the file in DNN's bin folder.
